version: '2.4'

services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    restart: always
    volumes:
      - db-data:/data/db:delegated

volumes:
  db-data: